# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "matvrus/kbot"
  tag: "v1.0.0-c81d3d8"
  arch: "amd64"
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
