# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: "matvrus"
  tag: "v1.0.0-45955d8"
  arch: "amd64"
  os: linux
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
ns:
  enable: true 
