name: KBOT-CICD

on:
  push:
    branches:
      - develop

env:
  ARCH: amd64
  REGISTRY: ghcr.io/${{ github.repository }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: GitHub Container login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build&Push
        env:
          APP: "kbot"
          REGISTRYDOC: ${{ secrets.DOCKERHUB_USERNAME }}
        run: make make image push ARCH=$ARCH REGISTRY=$REGISTRY

      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - run: echo "VERION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV

    - uses: mikefarah/yq@master
      with:
        cmd: yq -i '.image.tag=strenv(VERSION) | .image.arch=strenv(TARGETARCH)' helm/values.yaml

    - run: |
        git config user.name "github-actions"
        git config user.email github-actions@github.com
        git commit --allow-empty -m "update version $VERSION"
        git push