name: KBOT-CICD

on:
  push:
    branches:
      - "develop"

env:
  APP: kbot
  REGISTRY: ghcr.io
  REPOSITORY: ${{ github.actor }} # matvrus
  TARGETOS: linux #linux darwin windows
  TARGETARCH: amd64 #amd64 arm64
  HELM_CHART: helm
  GH_TOKEN: ${{ secrets.GIT_TOKEN }}

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run test
        run: make test

      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REPOSITORY }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Build&Push
        env:
          APP: ${{ env.APP }}
          REGISTRY: ${{ env.REGISTRY }}
          REPOSITORY: ${{ env.REPOSITORY }}
          TARGETOS: ${{ env.TARGETOS }}
          TARGETARCH: ${{ env.TARGETARCH }}
        run: make image push

      - name: Clean
        run: make clean TARGETARCH=$TARGETARCH

  cd:
    name: CD
    needs: ci
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set env.repository to lowercase
      run: echo "REPOSITORY=${REPOSITORY,,}" >> $GITHUB_ENV
    - run: 
        echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "REPOSITORY=${REPOSITORY,,}" >> $GITHUB_ENV
        echo "VER_NUM=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV 
        echo "VERSION=$(git describe --tags --abbrev=0)-$(git rev-parse --short HEAD)" >> $GITHUB_ENV


    - uses: mikefarah/yq@master
      with:
        cmd: |
          yq -i '.image.registry=strenv(REGISTRY) | .image.repository=strenv(REPOSITORY) | .image.tag=strenv(VERSION) | .image.os=strenv(TARGETOS) | .image.arch=strenv(TARGETARCH)' helm/values.yaml
          yq -i '.appVersion=strenv(VERSION) | .version=strenv(HELM_CHART)' helm/Chart.yaml
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add docs/$APP-$HELM_CHART.tgz
        git commit --allow-empty -am "update version $VERSION"
        git push
        if [ "$(gh release view $VER_NUM 2>&1 | grep 'release not found' | wc -l)" = 1 ]; then 
          gh release create $VER_NUM --title "NP Kbot $VER_NUM" --draft=false --prerelease=false --generate-notes --latest;
        fi
        if [ "$(gh release view $VER_NUM --json assets --jq 'map(.[].name)' 2>&1 | grep $APP-$HELM_CHART.tgz | wc -l)" -gt 0 ]; then
          gh release delete-asset $VER_NUM $APP-$HELM_CHART.tgz -y;
        fi
        gh release upload $VER_NUM docs/$APP-$HELM_CHART.tgz